[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

["dev/github.com/tuckerman/dotfiles"]
    type = "git-repo"
    url = "github.com:tuckerman/dotfiles.git"
    refreshPeriod = "1h"

["dev/github.com/tuckerman/obsidian"]
    type = "git-repo"
    url = "github.com:tuckerman/obsidian.git"
    refreshPeriod = "1h"

["dev/github.com/tuckerman/pge-hfp"]
    type = "git-repo"
    url = "github.com:tuckerman/pge-hfp.git"
    refreshPeriod = "1h"
