#!/bin/bash

# Useful variables
CHEZMOI_OS="{{ .chezmoi.os }}"
CHEZMOI_PROFILE="{{ .profile }}"

# Helper functions

if_one() {
  local var_name="$1"
  local var_value="${!var_name}"
  [ "$var_value" = "1" ] && return 0 || return 1
}

if_profile() {
  [ "${CHEZMOI_PROFILE}" = "${1}" ] && return 0
  return 1
}

if_os() {
  [ "${CHEZMOI_OS}" = "${1}" ] && return 0
  return 1
}

if_ephemeral() {
  return 1
}

if_headless() {
  {{ if .headless }}
  return 0
  {{ else }}
  return 1
  {{ end }}
}

if_command() {
  if command -v $1 &> /dev/null; then
    return 0
  else
    return 1
  fi
}

check_helper_loaded() {
  return 0
}

# Let's get started!
if_one CHEZMOI_SKIP_SCRIPTS && echo "Skipping $(basename "$0") because CHEZMOI_SKIP_SCRIPTS=1" && exit

if_one CHEZMOI_DEBUG && echo "[chezmoi script] Running $(basename "$0")"
