# This stops random sinks from AirPlay devices appearing in the list of available sinks.
# If you want to use AirPlay devices, set this to true and restart PipeWire.
context.properties = {
	module.raop = false
}
