[ids]
1532:02a6:797b7976

[main]
# The keyboard firmware emits leftcontrol for its Caps Lock key.
leftcontrol = overload(leftcontrol, esc)
leftshift = overload(leftshift, S-9)
rightshift = overload(shift, S-0)

[leftcontrol:C]
h = left
j = down
k = up
l = right

[leftshift:S]
rightshift = overload(shift, macro(S-9 S-0))
